name: sentiment_analysis
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - contourpy=1.2.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - expat=2.5.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=73.1
  - intel-openmp=2023.1.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libpng=1.6.39
  - libpq=12.17
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - lz4-c=1.9.4
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - mysql=5.7.24
  - ncurses=6.4
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.0.13
  - packaging=23.2
  - pcre2=10.42
  - pillow=10.2.0
  - pip=23.3.1
  - ply=3.11
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.11.8
  - python-tzdata=2023.3
  - qt-main=5.15.2
  - readline=8.2
  - seaborn=0.12.2
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiohttp==3.9.4
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anyio==4.3.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.14.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cachetools==5.3.3
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - comm==0.2.2
      - dataclasses-json==0.6.4
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - distro==1.9.0
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - google-ai-generativelanguage==0.6.1
      - google-api-core==2.18.0
      - google-api-python-client==2.125.0
      - google-auth==2.29.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.5.0
      - googleapis-common-protos==1.63.0
      - greenlet==3.0.3
      - grpcio==1.62.1
      - grpcio-status==1.62.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httplib2==0.22.0
      - httpx==0.27.0
      - idna==3.7
      - ipykernel==6.29.4
      - ipython==8.23.0
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.3
      - json5==0.9.25
      - jsonpatch==1.33
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.1.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.26.0
      - langchain==0.1.16
      - langchain-community==0.0.32
      - langchain-core==0.1.42
      - langchain-openai==0.1.3
      - langchain-text-splitters==0.0.1
      - langsmith==0.1.47
      - markupsafe==2.1.5
      - marshmallow==3.21.1
      - matplotlib-inline==0.1.6
      - mistune==3.0.2
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.3
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook-shim==0.2.4
      - openai==1.17.1
      - orjson==3.10.0
      - overrides==7.7.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - platformdirs==4.2.0
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.43
      - proto-plus==1.23.0
      - protobuf==4.25.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycparser==2.22
      - pydantic==2.7.0
      - pydantic-core==2.18.1
      - pygments==2.17.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-json-logger==2.0.7
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - referencing==0.34.0
      - regex==2023.12.25
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.0
      - rsa==4.9
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.5
      - sqlalchemy==2.0.29
      - stack-data==0.6.3
      - tabulate==0.9.0
      - tenacity==8.2.3
      - terminado==0.18.1
      - tiktoken==0.3.3
      - tinycss2==1.2.1
      - tomli==2.0.1
      - tornado==6.4
      - tqdm==4.66.2
      - traitlets==5.14.2
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.11.0
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - uri-template==1.3.0
      - uritemplate==4.1.1
      - urllib3==2.2.1
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - yarl==1.9.4
