[data]
root = "data"
external = "external/MAC"
interim = "interim/MAC"
processed = "processed/MAC"
raw = "raw/MAC"

mac_csv_filename = "MAC_corpus.csv"
preprocessed_mac_json = "MAC_corpus.json"


[output]
root = "output/MAC"
predictions = "predictions.mac.gpt3.5.csv"

[prompting]
system_message = "Predict the class of this Arabic review (e.g ternary classification), whether it's positive (return 1), neutral (return 0) or negative (return -1) review. Please do not return anything other than that."
gemini_system_message = "What is the sentiment of the following tweets? Answer with positive, negative, or neutral."

